---
# Source: shopping-list/templates/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: shopping-list-mysql-secret
  labels:
    helm.sh/chart: shopping-list-0.3.0
    app.kubernetes.io/name: shopping-list
    app.kubernetes.io/instance: shopping-list
    app.kubernetes.io/version: "0.2.11"
    app.kubernetes.io/managed-by: Helm
data:
  MYSQL_DATABASE: "c2hvcHBpbmctbGlzdA=="
  MYSQL_PASSWORD: "UDQkJHcwcmQ="
  MYSQL_ROOT_PASSWORD: "UjAwdFA0JCR3MHJk"
  MYSQL_USER: "c2hvcHBlcg=="
type: Opaque
---
# Source: shopping-list/templates/mysql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shopping-list-mysql-pvc
  labels:
    app: mysql
    helm.sh/chart: shopping-list-0.3.0
    app.kubernetes.io/name: shopping-list
    app.kubernetes.io/instance: shopping-list
    app.kubernetes.io/version: "0.2.11"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
---
# Source: shopping-list/templates/mysql.yaml
apiVersion: v1
kind: Service
metadata:
  name: shopping-list-mysql
  labels:
    helm.sh/chart: shopping-list-0.3.0
    app.kubernetes.io/name: shopping-list
    app.kubernetes.io/instance: shopping-list
    app.kubernetes.io/version: "0.2.11"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: mysql
    app.kubernetes.io/name: shopping-list
    app.kubernetes.io/instance: shopping-list
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
---
# Source: shopping-list/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: shopping-list-shopping-list
  labels:
    helm.sh/chart: shopping-list-0.3.0
    app.kubernetes.io/name: shopping-list
    app.kubernetes.io/instance: shopping-list
    app.kubernetes.io/version: "0.2.11"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: shopping-list
    app.kubernetes.io/name: shopping-list
    app.kubernetes.io/instance: shopping-list
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
# Source: shopping-list/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-list-mysql
  labels:
    app: mysql
    helm.sh/chart: shopping-list-0.3.0
    app.kubernetes.io/name: shopping-list
    app.kubernetes.io/instance: shopping-list
    app.kubernetes.io/version: "0.2.11"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      app.kubernetes.io/name: shopping-list
      app.kubernetes.io/instance: shopping-list
  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/name: shopping-list
        app.kubernetes.io/instance: shopping-list
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: shopping-list-mysql-secret
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: shopping-list-mysql-secret
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: shopping-list-mysql-secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: shopping-list-mysql-secret
        - name: TZ
          value: "Europe/Berlin"
        - name: LANG
          value: "C.UTF-8"
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: "cluster.local"
        image: mysql:latest
        name: mysql
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: shopping-list-mysql-pvc
---
# Source: shopping-list/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-list-shopping-list
  labels:
    app: shopping-list
    helm.sh/chart: shopping-list-0.3.0
    app.kubernetes.io/name: shopping-list
    app.kubernetes.io/instance: shopping-list
    app.kubernetes.io/version: "0.2.11"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-list
      app.kubernetes.io/name: shopping-list
      app.kubernetes.io/instance: shopping-list
  template:
    metadata:
      labels:
        app: shopping-list
        app.kubernetes.io/name: shopping-list
        app.kubernetes.io/instance: shopping-list
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: shopping-list-mysql
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: shopping-list-mysql-secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: shopping-list-mysql-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: shopping-list-mysql-secret
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: "cluster.local"
        image: ghcr.io/tim-krehan/shopping-list:v0.2.11
        name: shopping-list
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
