apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-shopping-list
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: shopping-list
    app.kubernetes.io/instance: shopping-list
    app.kubernetes.io/name: chart
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.shoppingList.ports | toYaml | nindent 2 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-shopping-list
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-shopping-list'
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "chart.fullname" . }}-tls